import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
public class delete extends javax.swing.JFrame {

 public static Connection con = null;
 public static        Statement st = null;
       String id;
       String role;
       

    public delete() {
        initComponents();
        fail.setVisible(false);
         success.setVisible(false);
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver Loaded");
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/newproject","root","root");
            System.out.println("Connected");
            
            st = con.createStatement();
            
            }
        catch(ClassNotFoundException e)
        {
            System.out.println(e);
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fail = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        id1 = new javax.swing.JTextField();
        role1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        success = new javax.swing.JLabel();
        exit1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Id              :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 130, 140, 27);

        fail.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        fail.setForeground(new java.awt.Color(204, 0, 51));
        fail.setText("Failed");
        jPanel1.add(fail);
        fail.setBounds(430, 390, 150, 27);

        reset.setBackground(new java.awt.Color(204, 204, 255));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 0, 102));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/resetnew.jpg"))); // NOI18N
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(240, 450, 70, 40);

        delete1.setBackground(new java.awt.Color(204, 204, 255));
        delete1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        delete1.setForeground(new java.awt.Color(0, 0, 102));
        delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/deletelogo.jpg"))); // NOI18N
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        jPanel1.add(delete1);
        delete1.setBounds(690, 450, 73, 40);

        id1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jPanel1.add(id1);
        id1.setBounds(350, 130, 130, 40);

        role1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jPanel1.add(role1);
        role1.setBounds(350, 230, 228, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("[ c , cpp , java , html , oops ]");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(590, 240, 330, 40);

        success.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        success.setForeground(new java.awt.Color(0, 0, 255));
        success.setText("Deleted Succesfully");
        jPanel1.add(success);
        success.setBounds(350, 330, 250, 27);

        exit1.setBackground(new java.awt.Color(204, 204, 255));
        exit1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exit1.setForeground(new java.awt.Color(0, 0, 102));
        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exitnewnew.jpg"))); // NOI18N
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        jPanel1.add(exit1);
        exit1.setBounds(470, 450, 73, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Language  : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 230, 180, 27);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/j1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1200, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
id1.setText("");
success.setVisible(false);
fail.setVisible(false);
role1.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed
public static void Del()
{
   try
        {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver Loaded");
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/newproject","root","root");
            System.out.println("Connected");
            
            st = con.createStatement();
            
            }
        catch(ClassNotFoundException e)
        {
            System.out.println(e);
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
 
    
}
    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
 delete.Del();
         id=id1.getText();
       role=role1.getText();
 try
{String sql = "DELETE FROM "+role+" where id ="+id+" ";
            
            int i = st.executeUpdate(sql);
            
            if(i>0)
            { success.setVisible(true);
                System.out.println(i+" Record Deleted");
                 id1.setText("");
                  role1.setText("");
                  this.setVisible(true);
            }
            else
            { fail.setVisible(true);
                System.out.println("Record Deletion Failed...");
            }
            con.close();
     
}
 catch(SQLException e)
        {
            System.out.println(e);
        }

    }//GEN-LAST:event_delete1ActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_exit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete1;
    private javax.swing.JButton exit1;
    private javax.swing.JLabel fail;
    private javax.swing.JTextField id1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reset;
    private javax.swing.JTextField role1;
    private javax.swing.JLabel success;
    // End of variables declaration//GEN-END:variables
}
