import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;

public class score extends javax.swing.JFrame {
 public static String Score;
 public static String newscore;
public static Connection con=null;
 public static Statement st=null;
 public static  ResultSet rs = null;
  //  public static String Name;

    /**
     * Creates new form score
     */
    public score() {
        initComponents();
     
    }
public score(String Name,int Score1,String Role) {
        initComponents();
      sc.setVisible(true);
  Score=String.valueOf(Score1);
        name.setText(Name);
     score.setText(Score);   
     role.setText(Role);
       try
        {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver Loaded");
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/newproject","root","root");
            System.out.println("Connected");
            
            st = con.createStatement();
            
            String sql = "Insert into highscore values('"+Score1+"')";
            
            int i = st.executeUpdate(sql);
            
            if(i>0)
            {
                System.out.println(i+" Record Inserted");
            }
            else
            {
                System.out.println("Record Insertion Failed...");
            }
            
              String sql1 = "SELECT max(score)from highscore ";
            rs = st.executeQuery(sql1);
            
            while(rs.next())
            {
               sc.setText(rs.getString(1));
            }
            con.close();
            
       
        }
        catch(ClassNotFoundException e)
        {
            System.out.println(e);
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        sc = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 243, 249));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Language :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 240, 123, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Name       :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 150, 122, 32);

        name.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(0, 102, 153));
        name.setText("name");
        jPanel1.add(name);
        name.setBounds(460, 160, 335, 32);

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("Score       :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 330, 118, 32);

        score.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        score.setForeground(new java.awt.Color(0, 102, 153));
        score.setText("score");
        jPanel1.add(score);
        score.setBounds(460, 320, 199, 32);

        role.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        role.setForeground(new java.awt.Color(0, 102, 153));
        role.setText("language");
        jPanel1.add(role);
        role.setBounds(460, 240, 222, 32);

        exit.setBackground(new java.awt.Color(0, 0, 102));
        exit.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exitnew.jpg"))); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(540, 430, 120, 40);

        sc.setBackground(new java.awt.Color(51, 153, 255));
        sc.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        sc.setForeground(new java.awt.Color(0, 0, 102));
        sc.setText("00");
        sc.setToolTipText("");
        jPanel1.add(sc);
        sc.setBounds(1040, 60, 63, 50);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Highest Score :");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(820, 60, 200, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/j1.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, -250, 1230, 1020);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        score sc1=new score();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new score().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel role;
    private javax.swing.JLabel sc;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
