
//import java.sql.SQLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class update extends javax.swing.JFrame {
public static Connection con=null;
 public static Statement st=null;
public static String role;
String id;
String question;
String op4;
String op3;
String op2;
String op1;
String answer;

/**
     * Creates new form update
     */
    public update() {
        initComponents();
        failed.setVisible(false);
        success.setVisible(false);
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver Loaded");
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/newproject","root","root");
            System.out.println("Connected");
            
            st = con.createStatement();
            
       
        }
        catch(ClassNotFoundException e)
        {
            System.out.println(e);
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }

    }
    public static void Submit()
    {
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver Loaded");
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/newproject","root","root");
            System.out.println("Connected");
            
            st = con.createStatement();
            
       
        }
        catch(ClassNotFoundException e)
        {
            System.out.println(e);
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id1 = new javax.swing.JTextField();
        role1 = new javax.swing.JTextField();
        op31 = new javax.swing.JTextField();
        op21 = new javax.swing.JTextField();
        op11 = new javax.swing.JTextField();
        question1 = new javax.swing.JTextField();
        answer1 = new javax.swing.JTextField();
        op41 = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        success = new javax.swing.JLabel();
        failed = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 239, 247));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("   Option 2");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 200, 96, 33);

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Option 3");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 240, 81, 33);

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Answer");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 330, 90, 33);

        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("INSERT A  QUESTION");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(540, 10, 340, 33);

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Option 4");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 290, 81, 33);

        jLabel6.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Question");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 120, 76, 33);

        jLabel7.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Language");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(130, 40, 76, 33);

        jLabel8.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("    Option 1");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 160, 119, 33);

        jLabel9.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("ID");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(130, 80, 71, 33);

        id1.setBackground(new java.awt.Color(204, 204, 204));
        id1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id1ActionPerformed(evt);
            }
        });
        jPanel1.add(id1);
        id1.setBounds(240, 90, 119, 26);

        role1.setBackground(new java.awt.Color(204, 204, 204));
        role1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(role1);
        role1.setBounds(220, 50, 108, 26);

        op31.setBackground(new java.awt.Color(204, 204, 204));
        op31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        op31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op31ActionPerformed(evt);
            }
        });
        jPanel1.add(op31);
        op31.setBounds(240, 250, 603, 26);

        op21.setBackground(new java.awt.Color(204, 204, 204));
        op21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        op21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op21ActionPerformed(evt);
            }
        });
        jPanel1.add(op21);
        op21.setBounds(240, 210, 593, 26);

        op11.setBackground(new java.awt.Color(204, 204, 204));
        op11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(op11);
        op11.setBounds(240, 170, 594, 26);

        question1.setBackground(new java.awt.Color(204, 204, 204));
        question1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(question1);
        question1.setBounds(240, 130, 604, 26);

        answer1.setBackground(new java.awt.Color(204, 204, 204));
        answer1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(answer1);
        answer1.setBounds(240, 340, 595, 26);

        op41.setBackground(new java.awt.Color(204, 204, 204));
        op41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(op41);
        op41.setBounds(240, 290, 595, 26);

        reset.setBackground(new java.awt.Color(0, 0, 153));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/resetnew.jpg"))); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(220, 500, 140, 40);

        success.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        success.setForeground(new java.awt.Color(153, 204, 255));
        success.setText("Record Inserted Successfully");
        jPanel1.add(success);
        success.setBounds(310, 440, 314, 33);

        failed.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        failed.setForeground(new java.awt.Color(204, 0, 0));
        failed.setText("FAILED");
        jPanel1.add(failed);
        failed.setBounds(430, 390, 60, 33);

        submit.setBackground(new java.awt.Color(0, 0, 153));
        submit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/submitnew.jpg"))); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(550, 500, 153, 40);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("_____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-30, 550, 1120, 16);

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText(" For Delete a Question click Delete Button");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(230, 580, 443, 21);

        j2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        j2.setForeground(new java.awt.Color(0, 102, 102));
        j2.setText("[ c , cpp , java , html , oops ]");
        j2.setToolTipText("");
        jPanel1.add(j2);
        j2.setBounds(360, 40, 320, 50);

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/deletelogo.jpg"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 620, 140, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/j1.jpg"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 1250, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void op31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op31ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
id1.setText("");        // TODO add your handling code here:
role1.setText("");
id1.setText("");
op11.setText("");
op21.setText("");
op31.setText("");
op41.setText("");
answer1.setText("");
question1.setText("");
success.setVisible(false);
failed.setVisible(false);

    }//GEN-LAST:event_resetActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
update.Submit();
failed.setVisible(false);
success.setVisible(false);
id=id1.getText();
     role=  role1.getText();
        question=question1.getText();
       op1 =op11.getText();
      // id =id1.getText();
      
         op2 =op21.getText();
       op3 =op31.getText();
       op4 =op41.getText();
       answer =answer1.getText();
      
       try
       {if( id!=null&& question!=null&&op1!=null&&op2!=null&&op3!=null&&op4!=null&&answer!=null&&!id.equals("")&&!question.equals("")&&!op1.equals("")&&!op2.equals("")&&!op3.equals("")&&!op4.equals("")&&!answer.equals(""))
       {
            String sql = "Insert into "+role+" values('"+id+"','"+question+"','"+op1+"','"+op2+"','"+op3+"','"+op4+"','"+answer+"')";
            System.out.println(sql);
            int i = st.executeUpdate(sql);
            
            if(i>0&& id!=null&& question!=null&&op1!=null&&op2!=null&&op3!=null&&op4!=null&&answer!=null&&!id.equals("")&&!question.equals("")&&!op1.equals("")&&!op2.equals("")&&!op3.equals("")&&!op4.equals("")&&!answer.equals(""))
            {
                 success.setVisible(true);
//this.setVisible(false);
                System.out.println(i+" Record Inserted");
                id1.setText("");        // TODO add your handling code here:
role1.setText("");
id1.setText("");
op11.setText("");
op21.setText("");
op31.setText("");
op41.setText("");
answer1.setText("");
question1.setText("");
            }}
            else
            {
               failed.setVisible(true);
                System.out.println("Record Insertion Failed...");
            }
            con.close();
       }
       catch(SQLException e)
       {System.out.println(e);}
        
      
        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
delete dt=new delete();
dt.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void op21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op21ActionPerformed

    private void id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id1ActionPerformed

      public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer1;
    private javax.swing.JLabel failed;
    private javax.swing.JTextField id1;
    private javax.swing.JLabel j2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField op11;
    private javax.swing.JTextField op21;
    private javax.swing.JTextField op31;
    private javax.swing.JTextField op41;
    private javax.swing.JTextField question1;
    private javax.swing.JButton reset;
    private javax.swing.JTextField role1;
    private javax.swing.JButton submit;
    private javax.swing.JLabel success;
    // End of variables declaration//GEN-END:variables
}
