/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author admin
 */
public class USER extends javax.swing.JFrame {
String Name;
String role;
int score=0;
String Password; 
 static Connection con=null;
 static Statement st=null;
 //failed.setVisible(false);
    /**
     * Creates new form USER
     */
    public USER() {
        initComponents();
        failed.setVisible(false);
        success.setVisible(false);
        
        jButton1.setEnabled(false);
     
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver Loaded");
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/newproject","root","root");
            System.out.println("Connected");
            
            st = con.createStatement();
            
       
        }
        catch(ClassNotFoundException e)
        {
            System.out.println(e);
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }

    }
    
    public static void Submit()
    {
        
       try
        {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver Loaded");
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/newproject","root","root");
            System.out.println("Connected");
            
            st = con.createStatement();
            
       
        }
        catch(ClassNotFoundException e)
        {
            System.out.println(e);
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        failed = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        j1 = new javax.swing.JLabel();
        role1 = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        j2 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        success = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        score1 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 249, 253));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Name              :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 110, 160, 50);

        name.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(430, 100, 157, 45);

        failed.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        failed.setForeground(new java.awt.Color(204, 0, 0));
        failed.setText(" Login Failed");
        jPanel1.add(failed);
        failed.setBounds(430, 370, 120, 37);

        submit.setBackground(new java.awt.Color(0, 0, 51));
        submit.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/log3.png"))); // NOI18N
        submit.setText("Login");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(450, 440, 150, 50);

        j1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        j1.setForeground(new java.awt.Color(0, 0, 51));
        j1.setText("Password         :");
        jPanel1.add(j1);
        j1.setBounds(230, 170, 160, 50);

        role1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        role1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                role1ActionPerformed(evt);
            }
        });
        jPanel1.add(role1);
        role1.setBounds(430, 250, 157, 45);

        password.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password);
        password.setBounds(430, 180, 157, 43);

        j2.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        j2.setForeground(new java.awt.Color(0, 51, 51));
        j2.setText("[ c , cpp , java , html , oops ]");
        jPanel1.add(j2);
        j2.setBounds(650, 260, 380, 50);

        reset.setBackground(new java.awt.Color(51, 255, 51));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/resetnew.jpg"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(190, 440, 131, 50);

        success.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        success.setForeground(new java.awt.Color(51, 0, 204));
        success.setText("Login Successfull");
        jPanel1.add(success);
        success.setBounds(410, 330, 180, 37);

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nextlogonew new.jpg"))); // NOI18N
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(730, 440, 140, 50);
        jPanel1.add(score1);
        score1.setBounds(607, 18, 66, 0);

        j3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        j3.setForeground(new java.awt.Color(0, 0, 51));
        j3.setText("Language         :");
        jPanel1.add(j3);
        j3.setBounds(230, 240, 180, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/j1.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1250, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
 
        
// TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
 USER.Submit();
Name=name.getText();
Password=password.getText();
      role=  role1.getText();
      
       try
       {
            String sql = "Insert into user values('"+Name+"','"+Password+"','"+role+"',0)";
            
            int i = st.executeUpdate(sql);
            
            if(i>0&& Name!=null&& Password!=null&& role!=null&&!Name.equals("")&&!role.equals("")&&!Password.equals(""))
            {//quiz qz=new quiz();
//qz.setVisible(true);
//this.setVisible(false);
                 success.setVisible(true);
                 failed.setVisible(false);
name.setText("");

password.setText("");
role1.setText("");

                System.out.println(i+" Record Inserted");
                jButton1.setEnabled(true);
                
            }
            else
            {
               failed.setVisible(true);
                System.out.println("Record Insertion Failed...");
            }
            con.close();}
       catch(SQLException e)
       {System.out.println(e);}
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void role1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_role1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_role1ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
failed.setVisible(false);
name.setText("");
success.setVisible(false);
password.setText("");
role1.setText("");


// TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        quiz qz=new quiz(Name,role);
qz.setVisible(true);
this.setVisible(false);
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new USER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel failed;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton reset;
    private javax.swing.JTextField role1;
    private javax.swing.JLabel score1;
    private javax.swing.JButton submit;
    private javax.swing.JLabel success;
    // End of variables declaration//GEN-END:variables
}
